import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { AnalysesList } from "@/components/AnalysesList";
import { Wordmark } from "@/components/Wordmark";
import { SignOutButton } from "@/components/SignOutButton";

export default async function Home() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login");
  }

  const email = user.email ?? "your account";
  const initial = email.charAt(0).toUpperCase();

  return (
    <>
      {/* Everything outside <AnalysesList> is print:hidden — "Download as
          PDF" prints only the report, not the app chrome around it. */}
      <header className="sticky top-0 z-20 border-b border-gray-200 bg-white/95 backdrop-blur print:hidden">
        <div className="mx-auto flex h-14 max-w-3xl items-center justify-between gap-3 px-4 sm:px-6">
          <Wordmark />
          <div className="flex min-w-0 items-center gap-3">
            <span
              role="img"
              aria-label={`Signed in as ${email}`}
              title={email}
              className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-100 text-sm font-semibold text-blue-800"
            >
              <span aria-hidden="true">{initial}</span>
            </span>
            <span
              aria-hidden="true"
              className="hidden max-w-56 truncate text-sm text-gray-600 sm:block"
            >
              {email}
            </span>
            <SignOutButton />
          </div>
        </div>
      </header>

      <main
        id="main"
        tabIndex={-1}
        className="mx-auto w-full max-w-3xl px-4 py-8 focus:outline-none sm:px-6 sm:py-12"
      >
        <div className="space-y-8">
          <div className="space-y-2 print:hidden">
            <h1 className="text-2xl font-semibold tracking-tight text-gray-900 sm:text-3xl">
              Audit a repo before you ship it
            </h1>
            <p className="max-w-2xl text-base leading-relaxed text-gray-600">
              Submit a public GitHub repository. Specialist agents review the
              code, propose an AWS deployment and flag security risks, then a
              reviewer checks their work.
            </p>
          </div>

          <AnalysesList />

          <p className="text-xs leading-relaxed text-gray-600 print:hidden">
            Reviews are generated by AI agents. Verify important findings before
            acting on them.
          </p>
        </div>
      </main>
    </>
  );
}
